project_name: tvd
before:
  hooks:
    - bash clientid_check.sh
release:
  github:
    owner: dbarbuzzi
    name: tvd
  draft: true
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32bit
    amd64: 64bit
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
build:
  binary: tvd
  ldflags: "-s -w -X main.Version={{ .Version }} -X main.ClientID={{ .Env.TVD_CLIENT_ID }}"
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386
  env:
    - CGO_ENABLED=0
brew:
  name: tvd
  github:
    owner: dbarbuzzi
    name: homebrew-tap
  commit_author:
    name: dbarbuzzi
    email: dbarbuzzi@gmail.com
  folder: Formula
  homepage: "https://github.com/dbarbuzzi/tvd"
  description: "Download Twitch VODs"
  test: |
    system "#{bin}/tvd --version"
  install: |
    bin.install "tvd"
scoop:
  bucket:
    owner: dbarbuzzi
    name: scoop-bucket
  commit_author:
    name: dbarbuzzi
    email: dbarbuzzi@gmail.com
  homepage: "https://github.com/dbarbuzzi/tvd"
  description: "Download Twitch VODs"
