project_name: tvd
before:
  hooks:
    - bash clientid_check.sh
release:
  github:
    owner: dbarbuzzi
    name: tvd
archives:
  -
    replacements:
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{.ProjectName}}_{{.Version}}_checksums.txt'
build:
  binary: tvd
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.ClientID={{.Env.TVD_CLIENT_ID}}
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0
brews:
  -
    name: tvd
    tap:
      owner: dbarbuzzi
      name: homebrew-tap
    commit_author:
      name: dbarbuzzi
      email: dbarbuzzi@gmail.com
    folder: Formula
    homepage: "https://github.com/dbarbuzzi/tvd"
    description: "Download Twitch VODs"
    test: |
      system "#{bin}/tvd --version"
    install: |
      bin.install "tvd"
scoop:
  bucket:
    owner: dbarbuzzi
    name: scoop-bucket
  commit_author:
    name: dbarbuzzi
    email: dbarbuzzi@gmail.com
  homepage: "https://github.com/dbarbuzzi/tvd"
  description: "Download Twitch VODs"
